### PR TITLE
Add `CTBuilder` options for setting behavior of regex.

### PR DESCRIPTION
**Pull request by ratmice**
This is a patch that I discussed in #399
It is still missing some odds and ends, e.g. it only currently works with `CTLexerBuilder` and is missing support within the runtime builders.  But it seemed a worthwhile place to stop and ponder if this is a viable approach.  I tried to do it using a mechanism that allows us to avoid adding a new builder function for each regex setting, It seemed at least worth trying however i'm not sure how I feel about how the actual calls to `RegexBuilder` now look.

This isn't something that I really need, or seems to be blocking anything to my knowledge, so that alone should maybe induce some skepticism about the idea.

- [X] works with CTLexerBuilder
- [ ] runtime builders?
- [ ] Should it use the `quote::ToTokens` trait instead of `Debug`?

### CODE REVIEW

**Comment by ltratt** [comment]
Like you, I think, I'm not 100% sure what the right approach here is. One thing that occurs to me looking at the code is that the `enum` variants are one more thing for people to remember, because they have to map those over to the regex crate functions (https://docs.rs/regex/1.7.1/regex/struct.RegexBuilder.html). Which makes me wonder: should we just expose function names that are identical to those in `RegexBuilder` (e.g. `pub fn case_insensitive(&mut self, yes: bool) -> ...`) ? Warning: this might be a terrible idea!

**Comment by ratmice** [comment]
Yeah, I guess the main benefit (which I entirely forgot to implement) of the approach that I took is that we can implement `Serialize`/`Deserialize` for the enum which can be helpful if I would expose these options in nimbleparse_lsp, so I think that is the underlying reason I tried that approach first.  I can have a look at the normal builder approach tomorrow though.

**Comment by ratmice** [comment]
FWIW I put the attempt at using normal builder style here: https://github.com/ratmice/grmtools/tree/regex_options_take_2

**Comment by ratmice** [comment]
Think i'll just close this one for now.

**Comment by ltratt** [comment]
> FWIW I put the attempt at using normal builder style here: https://github.com/ratmice/grmtools/tree/regex_options_take_2

Do you think this route can work? I'm not quite sure if it suffers from the problem you mentioned above or not.

**Comment by ratmice** [comment]
Yeah, it still does suffer from that problem.  The main missing piece of it is that there is no way to call the `LexParser::new_with_regex_options` function I added passing in options from `CTLexerBuilder` with regex_options being routed through `LexerDef::from_str` or `LRNonStreamingLexerDef::from_str`.  So it's mostly just public API decisions.  We can probably keep `from_str` letting it use the default options. But i'm mostly unsure what to do with from_str being a trait function.

**Comment by ltratt** [comment]
Hmm, yes, I don't have an immediately good answer to that :/

**Comment by ratmice** [comment]
Yeah, i'm pretty hesitant to make such changes API without a real motivating use case, so I don't think there is any immediate need. But I do plan on tinkering with a few potential things to see if I can come up with anything that seems worthwhile.

**Pull request closed without merging**
