### PR TITLE
Setup bors

### PR DESCRIPTION
**Pull request by ptersilie**

### CODE REVIEW

**Comment by ptersilie** [comment]
bors ping

**Comment by ptersilie** [comment]
bors test

**Comment by ptersilie** [comment]
bors test

**Comment by ptersilie** [comment]
bors try

**Comment by ltratt** [comment]
Sorry, I just realised that I'd forgotten to check that we're using stable for the main testing. We are, so I cancelled for nothing.

bors r+

**Comment by ltratt** [comment]
I'm just getting the branch settings correct. Hopefully I've now done the last one...

bors r+

**Pull request merged**
