### PR TITLE
It's hard to use the 'visibility' function with 'Visibility' being exported.

### PR DESCRIPTION
**Pull request by ltratt**
Fixes https://github.com/softdevteam/grmtools/issues/222.

### CODE REVIEW

**Comment by ptersilie** [comment]
Shouldn't the commit message be "without Visibility being exported"?

**Comment by ltratt** [comment]
Mea culpa! OK for me to force push an update?

**Comment by ptersilie** [comment]
Please do!

**Comment by ltratt** [comment]
Force pushed.

**Pull request merged**
