### PR TITLE
Clippy fixes

### PR DESCRIPTION
**Pull request by ltratt**
https://github.com/softdevteam/grmtools/commit/f4c2fbf6ad943e27f44c0908eb9e075e26769649 is more extensive than usual, but I generally prefer to keep Clippy warnings to zero, because it does highlight some useful things, and it's worth not losing them amongst the noise.

### CODE REVIEW

**Comment by ratmice** [comment]
The only thing I would note is if you run with `cargo clippy --enable-targets=all` 
one more `s.push_str(format!(...))` appears in lrlex/src/lib/parser.rs `exceed_tok_id_capacity()`.

Other than that, looks fine

**Comment by ltratt** [comment]
Weirdly, that invocation of clippy doesn't work for me, but I see the `push_str` anyway: fixed in f358cec.

**Comment by ratmice** [comment]
Sorry, that should have been *--all-targets*.

Please squash

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
