### PR TITLE
fix for issue #296

### PR DESCRIPTION
**Pull request by ratmice**
This adds a minimized testcase for issue #296, but I still need to look into the cause.

### CODE REVIEW

**Comment by ltratt** [comment]
I think you're saying this should bork as-is? No need to verify as bors will tell me :)

bors try

**Comment by ratmice** [comment]
Working on a fix, it happens when we insert a duplicate into the indexset, but then add the span to a vec regardless.
Then the indexes into the vec are off by one for each dupe.

**Comment by ratmice** [comment]
FYI, this one should be ready, just force pushing to keep in sync with master.

**Comment by ltratt** [comment]
Please squash (it would be nice to have the test and fix in one commit IMHO).

**Pull request merged**
