### PR TITLE
Add a type for warnings, and a spanned trait for warnings/errors.

### PR DESCRIPTION
**Pull request by ratmice**
This merely adds the types, modifies things so they'll work in a trait, due to traits not support `impl` in return type,
and implements the trait.

For some motivation for the trait, you can see the example using the [ariadne](https://crates.io/crates/ariadne/) crate
included in https://github.com/ratmice/grmtools/commit/eca699f9e2fe48d1030785eae6c2e06a95a8ee45 on a WIP [analysis](https://github.com/ratmice/grmtools/tree/analysis) branch that this has been
cherry-picked from. In that patch, there is a generic function `spanned_report<T: Spanned>`
used to build a report for both errors and warnings. I have included some output below.

```
Error:
   ╭─[erroneous.y:4:1]
   │
 4 │ C -> (): {};
   · ┬
   · ╰── Duplicated rule
 5 │ C -> (): B {};
   · ┬
   · ╰── Duplicate
───╯
Warning:
   ╭─[erroneous.y:4:1]
   │
 4 │ C -> (): {};
   · ┬
   · ╰── Unused rule
───╯
```

### CODE REVIEW

**Comment by ltratt** [comment]
Sorry this one has taken me so long!

bors

**Comment by ratmice** [comment]
No need to apologize, I fixed the links in [6813eb1](https://github.com/softdevteam/grmtools/pull/351/commits/6813eb1685ccc65bddf32c29821bc26f9031bde0)

**Comment by ratmice** [comment]
Squashed, 

P.S. I don't know if I'll get the next patch out before stepping out for a few days.
It is basically in a state where I could live with it, but unfortunately has some large
patch sections I've been having difficulty trying to split up, certainly will give it a try.

**Comment by ltratt** [comment]
Given how long I took to review this, I can't complain if you're delayed too! I hope things work out well at your end!

bors r+

**Pull request merged**
