### PR TITLE
Force %epp declaration values to be quoted.

### PR DESCRIPTION
**Pull request by ltratt**
What was:

```
  %epp A xyz
```

is now:

```
  %epp A "xyz"
```

Escaping works e.g.:

```
  %epp String "\"<String\""
```

If you want to test, the updated grammars are at https://github.com/softdevteam/grammars/commit/25d57ba890af7a54cd337d690462d94cb3665b0d.

### CODE REVIEW

**Comment by ptersilie** [comment]
I thought we agreed that one could use either double or single quotes, so that the user won't have to escape them, e.g. `%epp String '"<String"'`

**Comment by ltratt** [comment]
Yes, you can use either (see the tests). But escaping works too!

**Comment by ptersilie** [comment]
Nevermind, just saw the code implements this. I just assumed it doesn't because of your example in the PR desciption! Sorry!

**Comment by ptersilie** [comment]
Maybe we can add a small sentence to the commit message to say that single quotes are also supported?

**Comment by ltratt** [comment]
Done!

**Pull request merged**
