### PR TITLE
Changes to the (once was) `lexemes` module.

### PR DESCRIPTION
**Pull request by ltratt**
This PR first renames lrlex's `lexemes` module to `defaults` (https://github.com/softdevteam/grmtools/commit/5e5f4d8298ce7ee62cd4a188836a941f559353dd) and then removes an unnecessary bound on a struct therein (https://github.com/softdevteam/grmtools/commit/fe9a741fa8822c2b051400221b826389f7b1b0c9). Neither change is critical but makes reading and using lrlex a little easier.

### CODE REVIEW

**Comment by ratmice** [comment]
Looks good to me, if you feel it needs a squash, please squash, otherwise happy to r+ it as is.

**Comment by ltratt** [comment]
I think they're best kept separate if you're OK with that.

**Comment by ltratt** [comment]
Looks like rustdoc has changed a bit. Probably best to try this in another PR. Bear with me!

**Comment by ltratt** [comment]
@ratmice With luck this one should now work.

**Pull request merged**
